<wsdl:definitions
     name="socketService"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/socket/SocketAdapterApplication/ReceiveSocketMessageSBProject/socketService"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/socket/SocketAdapterApplication/ReceiveSocketMessageSBProject/socketService"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:msg_request="http://TargetNamespace.com/ServiceName"
     xmlns:msg_reply="http://waslley.souza.com.br/Employee"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="InboundRequestReply_plt" >
    <plt:role name="InboundRequestReply_role" >
      <plt:portType name="tns:InboundRequestReply_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://TargetNamespace.com/ServiceName" schemaLocation="../nxsd_requestSchema.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://waslley.souza.com.br/Employee" schemaLocation="../response.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Employees_msg_requsest">
        <wsdl:part name="Employees" element="msg_request:Employees"/>
    </wsdl:message>
    <wsdl:message name="Response_msg_reply">
        <wsdl:part name="Response" element="msg_reply:Response"/>
    </wsdl:message>
    <wsdl:portType name="InboundRequestReply_ptt">
        <wsdl:operation name="InboundRequestReply">
            <wsdl:input message="tns:Employees_msg_requsest"/>
            <wsdl:output message="tns:Response_msg_reply"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
