<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/socket/SocketAdapterApplication/ReceiveSocketMessageSBProject/socketService" name="socketService-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="socketService.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/socket/SocketAdapterApplication/ReceiveSocketMessageSBProject/socketService"/>
    <wsdl:binding name="InboundRequestReply_ptt-binding" type="soc:InboundRequestReply_ptt" xmlns:soc="http://xmlns.oracle.com/pcbpel/adapter/socket/SocketAdapterApplication/ReceiveSocketMessageSBProject/socketService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="InboundRequestReply">
            <soap:operation soapAction="InboundRequestReply"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>